### ISSUE TITLE
(bug) crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by vishallanke** [meinaart/cypress-plugin-snapshots#229]
Node version 17. Cypress 9.5. I am getting below error.  

```
The following error originated from your test code, not from Cypress.

  > crypto.randomBytes is not a function

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

at createToken ([webpack:///./node_modules/cypress-plugin-snapshots/src/config.js:6:1](http://localhost:59402/__/#))
    at ./node_modules/cypress-plugin-snapshots/src/config.js ([webpack:///./node_modules/cypress-plugin-snapshots/src/config.js:49:1](http://localhost:59402/__/#))
    at __webpack_require__ ([webpack:///webpack/bootstrap:19:1](http://localhost:59402/__/#))
    at ./node_modules/cypress-plugin-snapshots/src/ui.js ([webpack:///./node_modules/cypress-plugin-snapshots/src/ui.js:2:38](http://localhost:59402/__/#))
    at __webpack_require__ ([webpack:///webpack/bootstrap:19:1](http://localhost:59402/__/#))
```

**Comment by ricky-sandoval** [comment]
@vishallanke also getting this, were you able to find a workaround?
