### ISSUE TITLE
Error running plugin

### ISSUE THREAD

**Issue by RichieRunner** [meinaart/cypress-plugin-snapshots#55]
I'm seeing the following error when running `cypress open`. I have configured plugins as specified.

 Error running plugin

The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.

Error: listen EACCES 127.0.0.1:2121
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

**Comment by meinaart** [comment]
Are you allowed to run local servers? Otherwise you need to disable the server in the configuration. This does disable updating snapshots via the GUI.

**Comment by RichieRunner** [comment]
i have ran into the same issue, and tried changing the `serverPort` but still see `EACCES 127.0.0.1:2121`. I don't think it's reading from serverPort at all?

**Comment by RichieRunner** [comment]
solved; i had my `cypress.json` in the wrong place. this works
